# ponytail: 1 archivo, 3 targets. Tracing/logs diferidos.
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: pymes
    static_configs:
      - targets:
          - pymes-gateway:8080
          - pymes-auth-service:8081
          - pymes-core-service:8082
        labels:
          env: stg
    metrics_path: /actuator/prometheus
    scrape_timeout: 5s
